# Generated by Django 3.0.6 on 2020-05-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('product_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('basket', models.CharField(max_length=250)),
                ('purchase_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('customer_id', models.IntegerField()),
            ],
        ),
    ]
