# Generated by Django 3.0.6 on 2020-05-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='street_address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(max_length=250),
        ),
    ]
