# Generated by Django 3.0.6 on 2020-05-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='productname',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='producttype',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='productid',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='purchasecount',
            new_name='purchase_count',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='streetaddress',
            new_name='street_address',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
